//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syngenta.AgriCast.WebService.SynCryptographyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agriweb.syngenta-ais.com/", ConfigurationName="SynCryptographyService.SynCryptographySoap")]
    public interface SynCryptographySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agriweb.syngenta-ais.com/Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Encrypt(string strEncryptionText, string strKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agriweb.syngenta-ais.com/Decrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Decrypt(string strEncryptedText, string strKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SynCryptographySoapChannel : Syngenta.AgriCast.WebService.SynCryptographyService.SynCryptographySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynCryptographySoapClient : System.ServiceModel.ClientBase<Syngenta.AgriCast.WebService.SynCryptographyService.SynCryptographySoap>, Syngenta.AgriCast.WebService.SynCryptographyService.SynCryptographySoap {
        
        public SynCryptographySoapClient() {
        }
        
        public SynCryptographySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynCryptographySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynCryptographySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynCryptographySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode Encrypt(string strEncryptionText, string strKey) {
            return base.Channel.Encrypt(strEncryptionText, strKey);
        }
        
        public System.Xml.XmlNode Decrypt(string strEncryptedText, string strKey) {
            return base.Channel.Decrypt(strEncryptedText, strKey);
        }
    }
}
