//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Configuration;


//  
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TopNavigationSoap", Namespace="http://syngenta.TopNavigation.org/")]
public partial class TopNavigation : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback ExposeNavigationInXMLOperationCompleted;
    
    /// <remarks/>
    public TopNavigation() {
        //this.Url = "http://www.syngenta.com/_vti_bin/Topnavigation.asmx";
        this.Url = ConfigurationManager.AppSettings["mossUrl"].ToString();
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event ExposeNavigationInXMLCompletedEventHandler ExposeNavigationInXMLCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://syngenta.TopNavigation.org/HelloWorld", RequestNamespace="http://syngenta.TopNavigation.org/", ResponseNamespace="http://syngenta.TopNavigation.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://syngenta.TopNavigation.org/ExposeNavigationInXML", RequestNamespace="http://syngenta.TopNavigation.org/", ResponseNamespace="http://syngenta.TopNavigation.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode ExposeNavigationInXML(string serverName, string country, string countryCode, string countryLanguage) {
        object[] results = this.Invoke("ExposeNavigationInXML", new object[] {
                    serverName,
                    country,
                    countryCode,
                    countryLanguage});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExposeNavigationInXML(string serverName, string country, string countryCode, string countryLanguage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ExposeNavigationInXML", new object[] {
                    serverName,
                    country,
                    countryCode,
                    countryLanguage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndExposeNavigationInXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void ExposeNavigationInXMLAsync(string serverName, string country, string countryCode, string countryLanguage) {
        this.ExposeNavigationInXMLAsync(serverName, country, countryCode, countryLanguage, null);
    }
    
    /// <remarks/>
    public void ExposeNavigationInXMLAsync(string serverName, string country, string countryCode, string countryLanguage, object userState) {
        if ((this.ExposeNavigationInXMLOperationCompleted == null)) {
            this.ExposeNavigationInXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExposeNavigationInXMLOperationCompleted);
        }
        this.InvokeAsync("ExposeNavigationInXML", new object[] {
                    serverName,
                    country,
                    countryCode,
                    countryLanguage}, this.ExposeNavigationInXMLOperationCompleted, userState);
    }
    
    private void OnExposeNavigationInXMLOperationCompleted(object arg) {
        if ((this.ExposeNavigationInXMLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ExposeNavigationInXMLCompleted(this, new ExposeNavigationInXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ExposeNavigationInXMLCompletedEventHandler(object sender, ExposeNavigationInXMLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExposeNavigationInXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ExposeNavigationInXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}
