//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class service {
    
    private string nameField;
    
    private string extNavigationField;
    
    private bool securedField;
    
    private string encryptKeyField;
    
    private string allowedRolesField;
    
    private serviceEmailSettings emailSettingsField;
    
    private serviceCultureSettings cultureSettingsField;
    
    private serviceUnitsSettings unitsSettingsField;
    
    private serviceLocationSearch locationSearchField;
    
    private serviceServicePage[] servicePageField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string extNavigation {
        get {
            return this.extNavigationField;
        }
        set {
            this.extNavigationField = value;
        }
    }
    
    /// <remarks/>
    public bool secured {
        get {
            return this.securedField;
        }
        set {
            this.securedField = value;
        }
    }
    
    /// <remarks/>
    public string encryptKey {
        get {
            return this.encryptKeyField;
        }
        set {
            this.encryptKeyField = value;
        }
    }
    
    /// <remarks/>
    public string allowedRoles {
        get {
            return this.allowedRolesField;
        }
        set {
            this.allowedRolesField = value;
        }
    }
    
    /// <remarks/>
    public serviceEmailSettings emailSettings {
        get {
            return this.emailSettingsField;
        }
        set {
            this.emailSettingsField = value;
        }
    }
    
    /// <remarks/>
    public serviceCultureSettings cultureSettings {
        get {
            return this.cultureSettingsField;
        }
        set {
            this.cultureSettingsField = value;
        }
    }
    
    /// <remarks/>
    public serviceUnitsSettings unitsSettings {
        get {
            return this.unitsSettingsField;
        }
        set {
            this.unitsSettingsField = value;
        }
    }
    
    /// <remarks/>
    public serviceLocationSearch locationSearch {
        get {
            return this.locationSearchField;
        }
        set {
            this.locationSearchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("servicePage")]
    public serviceServicePage[] servicePage {
        get {
            return this.servicePageField;
        }
        set {
            this.servicePageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceEmailSettings {
    
    private string senderNameField;
    
    private string senderAddressField;
    
    private string subjectField;
    
    private object defaultBodyField;
    
    /// <remarks/>
    public string senderName {
        get {
            return this.senderNameField;
        }
        set {
            this.senderNameField = value;
        }
    }
    
    /// <remarks/>
    public string senderAddress {
        get {
            return this.senderAddressField;
        }
        set {
            this.senderAddressField = value;
        }
    }
    
    /// <remarks/>
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    public object defaultBody {
        get {
            return this.defaultBodyField;
        }
        set {
            this.defaultBodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceCultureSettings {
    
    private serviceCultureSettingsCulture[] allowedCultureCodesField;
    
    private string defaultField;
    
    private bool useIPCultureField;
    
    private bool useBrowserLangField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("culture", IsNullable=false)]
    public serviceCultureSettingsCulture[] allowedCultureCodes {
        get {
            return this.allowedCultureCodesField;
        }
        set {
            this.allowedCultureCodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool useIPCulture {
        get {
            return this.useIPCultureField;
        }
        set {
            this.useIPCultureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool useBrowserLang {
        get {
            return this.useBrowserLangField;
        }
        set {
            this.useBrowserLangField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceCultureSettingsCulture {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceUnitsSettings {
    
    private string unitsField;
    
    private serviceUnitsSettingsCustom customField;
    
    /// <remarks/>
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public serviceUnitsSettingsCustom custom {
        get {
            return this.customField;
        }
        set {
            this.customField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceUnitsSettingsCustom {
    
    private string windField;
    
    /// <remarks/>
    public string Wind {
        get {
            return this.windField;
        }
        set {
            this.windField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceLocationSearch {
    
    private serviceLocationSearchArea[] allowedCountriesField;
    
    private string nameField;
    
    private string defaultLocationField;
    
    private bool useIPLocationField;
    
    private string providerField;
    
    private byte resultCountField;
    
    private bool showMapField;
    
    private bool showMapFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("area", IsNullable=false)]
    public serviceLocationSearchArea[] allowedCountries {
        get {
            return this.allowedCountriesField;
        }
        set {
            this.allowedCountriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultLocation {
        get {
            return this.defaultLocationField;
        }
        set {
            this.defaultLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool useIPLocation {
        get {
            return this.useIPLocationField;
        }
        set {
            this.useIPLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte resultCount {
        get {
            return this.resultCountField;
        }
        set {
            this.resultCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool showMap {
        get {
            return this.showMapField;
        }
        set {
            this.showMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showMapSpecified {
        get {
            return this.showMapFieldSpecified;
        }
        set {
            this.showMapFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceLocationSearchArea {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePage {
    
    private serviceServicePagePageSettings pageSettingsField;
    
    private serviceServicePageNearbyDataPoint nearbyDataPointField;
    
    private serviceServicePageAgriInfo agriInfoField;
    
    private serviceServicePageTblDaysRows[] tblDaysRowsField;
    
    private serviceServicePageIcon[] iconField;
    
    private serviceServicePageChart[] chartField;
    
    private serviceServicePageLegend[] legendField;
    
    private serviceServicePageTblSeriesRows[] tblSeriesRowsField;
    
    private serviceServicePageWindIcon[] windIconField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private bool defaultPageField;
    
    private bool defaultPageFieldSpecified;
    
    private string templateField;
    
    private bool widgetOnlyField;
    
    private bool widgetOnlyFieldSpecified;
    
    /// <remarks/>
    public serviceServicePagePageSettings pageSettings {
        get {
            return this.pageSettingsField;
        }
        set {
            this.pageSettingsField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageNearbyDataPoint nearbyDataPoint {
        get {
            return this.nearbyDataPointField;
        }
        set {
            this.nearbyDataPointField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageAgriInfo agriInfo {
        get {
            return this.agriInfoField;
        }
        set {
            this.agriInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tblDaysRows")]
    public serviceServicePageTblDaysRows[] tblDaysRows {
        get {
            return this.tblDaysRowsField;
        }
        set {
            this.tblDaysRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public serviceServicePageIcon[] icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chart")]
    public serviceServicePageChart[] chart {
        get {
            return this.chartField;
        }
        set {
            this.chartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legend")]
    public serviceServicePageLegend[] legend {
        get {
            return this.legendField;
        }
        set {
            this.legendField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tblSeriesRows")]
    public serviceServicePageTblSeriesRows[] tblSeriesRows {
        get {
            return this.tblSeriesRowsField;
        }
        set {
            this.tblSeriesRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windIcon")]
    public serviceServicePageWindIcon[] windIcon {
        get {
            return this.windIconField;
        }
        set {
            this.windIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool defaultPage {
        get {
            return this.defaultPageField;
        }
        set {
            this.defaultPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultPageSpecified {
        get {
            return this.defaultPageFieldSpecified;
        }
        set {
            this.defaultPageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string template {
        get {
            return this.templateField;
        }
        set {
            this.templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool widgetOnly {
        get {
            return this.widgetOnlyField;
        }
        set {
            this.widgetOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widgetOnlySpecified {
        get {
            return this.widgetOnlyFieldSpecified;
        }
        set {
            this.widgetOnlyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePagePageSettings {
    
    private string allowFavoritesField;
    
    private string allowPrintPageField;
    
    private string allowEmailField;
    
    private string allowExportToExcelField;
    
    private string allowFeedbackField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowFavorites {
        get {
            return this.allowFavoritesField;
        }
        set {
            this.allowFavoritesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowPrintPage {
        get {
            return this.allowPrintPageField;
        }
        set {
            this.allowPrintPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowEmail {
        get {
            return this.allowEmailField;
        }
        set {
            this.allowEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowExportToExcel {
        get {
            return this.allowExportToExcelField;
        }
        set {
            this.allowExportToExcelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowFeedback {
        get {
            return this.allowFeedbackField;
        }
        set {
            this.allowFeedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageNearbyDataPoint {
    
    private string nameField;
    
    private string defaultDataSourceField;
    
    private ushort maxAllowedDistanceField;
    
    private ushort maxAllowedAltitudeField;
    
    private ushort resultCountField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultDataSource {
        get {
            return this.defaultDataSourceField;
        }
        set {
            this.defaultDataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort maxAllowedDistance {
        get {
            return this.maxAllowedDistanceField;
        }
        set {
            this.maxAllowedDistanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort maxAllowedAltitude {
        get {
            return this.maxAllowedAltitudeField;
        }
        set {
            this.maxAllowedAltitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort resultCount {
        get {
            return this.resultCountField;
        }
        set {
            this.resultCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfo {
    
    private serviceServicePageAgriInfoChart chartField;
    
    private serviceServicePageAgriInfoWeather weatherField;
    
    private serviceServicePageAgriInfoGdd gddField;
    
    private string nameField;
    
    private string defaultStartDateField;
    
    private string defaultEndDateField;
    
    private string defaultTemporalAggregationField;
    
    /// <remarks/>
    public serviceServicePageAgriInfoChart chart {
        get {
            return this.chartField;
        }
        set {
            this.chartField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageAgriInfoWeather weather {
        get {
            return this.weatherField;
        }
        set {
            this.weatherField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageAgriInfoGdd gdd {
        get {
            return this.gddField;
        }
        set {
            this.gddField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultStartDate {
        get {
            return this.defaultStartDateField;
        }
        set {
            this.defaultStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultEndDate {
        get {
            return this.defaultEndDateField;
        }
        set {
            this.defaultEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultTemporalAggregation {
        get {
            return this.defaultTemporalAggregationField;
        }
        set {
            this.defaultTemporalAggregationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoChart {
    
    private serviceServicePageAgriInfoChartPrimaryAxis primaryAxisField;
    
    private serviceServicePageAgriInfoChartSecondaryAxis secondaryAxisField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private ushort widthField;
    
    private ushort heightField;
    
    private string dataSourceField;
    
    private string watermarkField;
    
    /// <remarks/>
    public serviceServicePageAgriInfoChartPrimaryAxis PrimaryAxis {
        get {
            return this.primaryAxisField;
        }
        set {
            this.primaryAxisField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageAgriInfoChartSecondaryAxis SecondaryAxis {
        get {
            return this.secondaryAxisField;
        }
        set {
            this.secondaryAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string watermark {
        get {
            return this.watermarkField;
        }
        set {
            this.watermarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoChartPrimaryAxis {
    
    private string trnsTagField;
    
    private string scaleTypeField;
    
    private sbyte minValueField;
    
    private sbyte maxValueField;
    
    private sbyte minValueImperialField;
    
    private bool minValueImperialFieldSpecified;
    
    private sbyte maxValueImperialField;
    
    private bool maxValueImperialFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scaleType {
        get {
            return this.scaleTypeField;
        }
        set {
            this.scaleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValueImperial {
        get {
            return this.minValueImperialField;
        }
        set {
            this.minValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minValueImperialSpecified {
        get {
            return this.minValueImperialFieldSpecified;
        }
        set {
            this.minValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValueImperial {
        get {
            return this.maxValueImperialField;
        }
        set {
            this.maxValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxValueImperialSpecified {
        get {
            return this.maxValueImperialFieldSpecified;
        }
        set {
            this.maxValueImperialFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoChartSecondaryAxis {
    
    private string trnsTagField;
    
    private string scaleTypeField;
    
    private sbyte minValueField;
    
    private sbyte maxValueField;
    
    private sbyte minValueImperialField;
    
    private bool minValueImperialFieldSpecified;
    
    private sbyte maxValueImperialField;
    
    private bool maxValueImperialFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scaleType {
        get {
            return this.scaleTypeField;
        }
        set {
            this.scaleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValueImperial {
        get {
            return this.minValueImperialField;
        }
        set {
            this.minValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minValueImperialSpecified {
        get {
            return this.minValueImperialFieldSpecified;
        }
        set {
            this.minValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValueImperial {
        get {
            return this.maxValueImperialField;
        }
        set {
            this.maxValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxValueImperialSpecified {
        get {
            return this.maxValueImperialFieldSpecified;
        }
        set {
            this.maxValueImperialFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoWeather {
    
    private serviceServicePageAgriInfoWeatherNode[] nodeField;
    
    private string nameField;
    
    private string trnTagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("node")]
    public serviceServicePageAgriInfoWeatherNode[] node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnTag {
        get {
            return this.trnTagField;
        }
        set {
            this.trnTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoWeatherNode {
    
    private serviceServicePageAgriInfoWeatherNodeSerie[] seriesField;
    
    private string idField;
    
    private string trnsTagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serie", IsNullable=false)]
    public serviceServicePageAgriInfoWeatherNodeSerie[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoWeatherNodeSerie {
    
    private serviceServicePageAgriInfoWeatherNodeSerieAdvancedOption advancedOptionField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    private bool isCheckedField;
    
    private bool isCheckedFieldSpecified;
    
    private string galleryField;
    
    private bool stackedField;
    
    private bool stackedFieldSpecified;
    
    private string colorField;
    
    private string markertypeField;
    
    private string axispositionField;
    
    private bool advancedOption1Field;
    
    private bool advancedOption1FieldSpecified;
    
    private string labelTextField;
    
    /// <remarks/>
    public serviceServicePageAgriInfoWeatherNodeSerieAdvancedOption advancedOption {
        get {
            return this.advancedOptionField;
        }
        set {
            this.advancedOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isChecked {
        get {
            return this.isCheckedField;
        }
        set {
            this.isCheckedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isCheckedSpecified {
        get {
            return this.isCheckedFieldSpecified;
        }
        set {
            this.isCheckedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gallery {
        get {
            return this.galleryField;
        }
        set {
            this.galleryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool stacked {
        get {
            return this.stackedField;
        }
        set {
            this.stackedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stackedSpecified {
        get {
            return this.stackedFieldSpecified;
        }
        set {
            this.stackedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string markertype {
        get {
            return this.markertypeField;
        }
        set {
            this.markertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string axisposition {
        get {
            return this.axispositionField;
        }
        set {
            this.axispositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("advancedOption")]
    public bool advancedOption1 {
        get {
            return this.advancedOption1Field;
        }
        set {
            this.advancedOption1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool advancedOption1Specified {
        get {
            return this.advancedOption1FieldSpecified;
        }
        set {
            this.advancedOption1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labelText {
        get {
            return this.labelTextField;
        }
        set {
            this.labelTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoWeatherNodeSerieAdvancedOption {
    
    private string allowedAggregationFunctionField;
    
    private string allowAccumalationField;
    
    private ushort minComparisonYearField;
    
    private bool minComparisonYearFieldSpecified;
    
    private string trendField;
    
    private string altitudeAdjustmentField;
    
    /// <remarks/>
    public string allowedAggregationFunction {
        get {
            return this.allowedAggregationFunctionField;
        }
        set {
            this.allowedAggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    public string allowAccumalation {
        get {
            return this.allowAccumalationField;
        }
        set {
            this.allowAccumalationField = value;
        }
    }
    
    /// <remarks/>
    public ushort minComparisonYear {
        get {
            return this.minComparisonYearField;
        }
        set {
            this.minComparisonYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minComparisonYearSpecified {
        get {
            return this.minComparisonYearFieldSpecified;
        }
        set {
            this.minComparisonYearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string trend {
        get {
            return this.trendField;
        }
        set {
            this.trendField = value;
        }
    }
    
    /// <remarks/>
    public string altitudeAdjustment {
        get {
            return this.altitudeAdjustmentField;
        }
        set {
            this.altitudeAdjustmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoGdd {
    
    private serviceServicePageAgriInfoGddSerie[] seriesField;
    
    private string nameField;
    
    private string trnTagField;
    
    private string defaultMethodField;
    
    private ushort defaultBaseField;
    
    private ushort defaultCapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serie", IsNullable=false)]
    public serviceServicePageAgriInfoGddSerie[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnTag {
        get {
            return this.trnTagField;
        }
        set {
            this.trnTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultMethod {
        get {
            return this.defaultMethodField;
        }
        set {
            this.defaultMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort defaultBase {
        get {
            return this.defaultBaseField;
        }
        set {
            this.defaultBaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort defaultCap {
        get {
            return this.defaultCapField;
        }
        set {
            this.defaultCapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoGddSerie {
    
    private serviceServicePageAgriInfoGddSerieAdvancedOption advancedOptionField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private string axispositionField;
    
    private string aggregationFunctionField;
    
    private bool advancedOption1Field;
    
    private bool advancedOption1FieldSpecified;
    
    private string galleryField;
    
    private string colorPaletteNameField;
    
    private bool stackedField;
    
    private bool stackedFieldSpecified;
    
    private string textColorField;
    
    private string labelTextField;
    
    private string colorField;
    
    private string markertypeField;
    
    /// <remarks/>
    public serviceServicePageAgriInfoGddSerieAdvancedOption advancedOption {
        get {
            return this.advancedOptionField;
        }
        set {
            this.advancedOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string axisposition {
        get {
            return this.axispositionField;
        }
        set {
            this.axispositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("advancedOption")]
    public bool advancedOption1 {
        get {
            return this.advancedOption1Field;
        }
        set {
            this.advancedOption1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool advancedOption1Specified {
        get {
            return this.advancedOption1FieldSpecified;
        }
        set {
            this.advancedOption1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gallery {
        get {
            return this.galleryField;
        }
        set {
            this.galleryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colorPaletteName {
        get {
            return this.colorPaletteNameField;
        }
        set {
            this.colorPaletteNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool stacked {
        get {
            return this.stackedField;
        }
        set {
            this.stackedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stackedSpecified {
        get {
            return this.stackedFieldSpecified;
        }
        set {
            this.stackedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string textColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labelText {
        get {
            return this.labelTextField;
        }
        set {
            this.labelTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string markertype {
        get {
            return this.markertypeField;
        }
        set {
            this.markertypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageAgriInfoGddSerieAdvancedOption {
    
    private string methodField;
    
    private string baseField;
    
    private string capField;
    
    /// <remarks/>
    public string method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    public string cap {
        get {
            return this.capField;
        }
        set {
            this.capField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblDaysRows {
    
    private serviceServicePageTblDaysRowsSeries seriesField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private bool collapsibleField;
    
    private bool collapsibleFieldSpecified;
    
    private string dataSourceField;
    
    private sbyte startDateField;
    
    private sbyte endDateField;
    
    private string temporalAggregationField;
    
    private string rulesetField;
    
    private string colorPaletteNameField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    
    /// <remarks/>
    public serviceServicePageTblDaysRowsSeries series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool collapsible {
        get {
            return this.collapsibleField;
        }
        set {
            this.collapsibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool collapsibleSpecified {
        get {
            return this.collapsibleFieldSpecified;
        }
        set {
            this.collapsibleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string temporalAggregation {
        get {
            return this.temporalAggregationField;
        }
        set {
            this.temporalAggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ruleset {
        get {
            return this.rulesetField;
        }
        set {
            this.rulesetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colorPaletteName {
        get {
            return this.colorPaletteNameField;
        }
        set {
            this.colorPaletteNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblDaysRowsSeries {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legend", typeof(serviceServicePageTblDaysRowsSeriesLegend))]
    [System.Xml.Serialization.XmlElementAttribute("serie", typeof(serviceServicePageTblDaysRowsSeriesSerie))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblDaysRowsSeriesLegend {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string htmlPathField;
    
    private bool collapsibleField;
    
    private bool collapsibleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string htmlPath {
        get {
            return this.htmlPathField;
        }
        set {
            this.htmlPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool collapsible {
        get {
            return this.collapsibleField;
        }
        set {
            this.collapsibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool collapsibleSpecified {
        get {
            return this.collapsibleFieldSpecified;
        }
        set {
            this.collapsibleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblDaysRowsSeriesSerie {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    private string colorPaletteNameField;
    
    private string rulesetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colorPaletteName {
        get {
            return this.colorPaletteNameField;
        }
        set {
            this.colorPaletteNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ruleset {
        get {
            return this.rulesetField;
        }
        set {
            this.rulesetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageIcon {
    
    private serviceServicePageIconSerie[] seriesField;
    
    private string nameField;
    
    private bool plotColumnHeaderField;
    
    private bool plotColumnHeaderFieldSpecified;
    
    private string dataSourceField;
    
    private sbyte startDateField;
    
    private sbyte endDateField;
    
    private string temporalAggregationField;
    
    private string imageSetNameField;
    
    private byte transparencyField;
    
    private byte widthField;
    
    private byte heightField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serie", IsNullable=false)]
    public serviceServicePageIconSerie[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool plotColumnHeader {
        get {
            return this.plotColumnHeaderField;
        }
        set {
            this.plotColumnHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool plotColumnHeaderSpecified {
        get {
            return this.plotColumnHeaderFieldSpecified;
        }
        set {
            this.plotColumnHeaderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string temporalAggregation {
        get {
            return this.temporalAggregationField;
        }
        set {
            this.temporalAggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imageSetName {
        get {
            return this.imageSetNameField;
        }
        set {
            this.imageSetNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte transparency {
        get {
            return this.transparencyField;
        }
        set {
            this.transparencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageIconSerie {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageChart {
    
    private serviceServicePageChartPrimaryAxis primaryAxisField;
    
    private serviceServicePageChartSecondaryAxis secondaryAxisField;
    
    private serviceServicePageChartSerie[] seriesField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private ushort widthField;
    
    private ushort heightField;
    
    private string dataSourceField;
    
    private sbyte startDateField;
    
    private sbyte endDateField;
    
    private string temporalAggregationField;
    
    private byte labelstepField;
    
    private bool labelstepFieldSpecified;
    
    private string watermarkField;
    
    private bool todayMarkerField;
    
    private string plotShadesField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    
    /// <remarks/>
    public serviceServicePageChartPrimaryAxis PrimaryAxis {
        get {
            return this.primaryAxisField;
        }
        set {
            this.primaryAxisField = value;
        }
    }
    
    /// <remarks/>
    public serviceServicePageChartSecondaryAxis SecondaryAxis {
        get {
            return this.secondaryAxisField;
        }
        set {
            this.secondaryAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serie", IsNullable=false)]
    public serviceServicePageChartSerie[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string temporalAggregation {
        get {
            return this.temporalAggregationField;
        }
        set {
            this.temporalAggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte labelstep {
        get {
            return this.labelstepField;
        }
        set {
            this.labelstepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool labelstepSpecified {
        get {
            return this.labelstepFieldSpecified;
        }
        set {
            this.labelstepFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string watermark {
        get {
            return this.watermarkField;
        }
        set {
            this.watermarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool TodayMarker {
        get {
            return this.todayMarkerField;
        }
        set {
            this.todayMarkerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string plotShades {
        get {
            return this.plotShadesField;
        }
        set {
            this.plotShadesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageChartPrimaryAxis {
    
    private string trnsTagField;
    
    private string scaleTypeField;
    
    private sbyte minValueField;
    
    private sbyte maxValueField;
    
    private sbyte minValueImperialField;
    
    private bool minValueImperialFieldSpecified;
    
    private sbyte maxValueImperialField;
    
    private bool maxValueImperialFieldSpecified;
    
    private string textColorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scaleType {
        get {
            return this.scaleTypeField;
        }
        set {
            this.scaleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValueImperial {
        get {
            return this.minValueImperialField;
        }
        set {
            this.minValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minValueImperialSpecified {
        get {
            return this.minValueImperialFieldSpecified;
        }
        set {
            this.minValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValueImperial {
        get {
            return this.maxValueImperialField;
        }
        set {
            this.maxValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxValueImperialSpecified {
        get {
            return this.maxValueImperialFieldSpecified;
        }
        set {
            this.maxValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string textColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageChartSecondaryAxis {
    
    private string trnsTagField;
    
    private string scaleTypeField;
    
    private sbyte minValueField;
    
    private sbyte maxValueField;
    
    private sbyte minValueImperialField;
    
    private bool minValueImperialFieldSpecified;
    
    private sbyte maxValueImperialField;
    
    private bool maxValueImperialFieldSpecified;
    
    private string textColorField;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    private bool isInvisibleField;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scaleType {
        get {
            return this.scaleTypeField;
        }
        set {
            this.scaleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte minValueImperial {
        get {
            return this.minValueImperialField;
        }
        set {
            this.minValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minValueImperialSpecified {
        get {
            return this.minValueImperialFieldSpecified;
        }
        set {
            this.minValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte maxValueImperial {
        get {
            return this.maxValueImperialField;
        }
        set {
            this.maxValueImperialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxValueImperialSpecified {
        get {
            return this.maxValueImperialFieldSpecified;
        }
        set {
            this.maxValueImperialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string textColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isInvisible
    {
        get
        {
            return this.isInvisibleField;
        }
        set
        {
            this.isInvisibleField = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageChartSerie {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    private string galleryField;
    
    private bool stackedField;
    
    private string colorField;
    
    private string markertypeField;
    
    private string axispositionField;
    
    private bool invertedField;
    
    private bool invertedFieldSpecified;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    private bool isInvisibleField;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gallery {
        get {
            return this.galleryField;
        }
        set {
            this.galleryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool stacked {
        get {
            return this.stackedField;
        }
        set {
            this.stackedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string markertype {
        get {
            return this.markertypeField;
        }
        set {
            this.markertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string axisposition {
        get {
            return this.axispositionField;
        }
        set {
            this.axispositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool inverted {
        get {
            return this.invertedField;
        }
        set {
            this.invertedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool invertedSpecified {
        get {
            return this.invertedFieldSpecified;
        }
        set {
            this.invertedFieldSpecified = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isInvisible
    {
        get
        {
            return this.isInvisibleField;
        }
        set
        {
            this.isInvisibleField = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageLegend {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string htmlPathField;
    
    private bool collapsibleField;
    
    private bool collapsibleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string htmlPath {
        get {
            return this.htmlPathField;
        }
        set {
            this.htmlPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool collapsible {
        get {
            return this.collapsibleField;
        }
        set {
            this.collapsibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool collapsibleSpecified {
        get {
            return this.collapsibleFieldSpecified;
        }
        set {
            this.collapsibleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblSeriesRows {
    
    private serviceServicePageTblSeriesRowsSeries seriesField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private string plotColumnHeaderField;
    
    private string dataSourceField;
    
    private bool collapsibleField;
    
    private bool collapsibleFieldSpecified;
    
    private sbyte startDateField;
    
    private sbyte endDateField;
    
    private string temporalAggregationField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    
    private string rulesetField;
    
    private string colorPaletteNameField;
    
    /// <remarks/>
    public serviceServicePageTblSeriesRowsSeries series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string plotColumnHeader {
        get {
            return this.plotColumnHeaderField;
        }
        set {
            this.plotColumnHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool collapsible {
        get {
            return this.collapsibleField;
        }
        set {
            this.collapsibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool collapsibleSpecified {
        get {
            return this.collapsibleFieldSpecified;
        }
        set {
            this.collapsibleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string temporalAggregation {
        get {
            return this.temporalAggregationField;
        }
        set {
            this.temporalAggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ruleset {
        get {
            return this.rulesetField;
        }
        set {
            this.rulesetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colorPaletteName {
        get {
            return this.colorPaletteNameField;
        }
        set {
            this.colorPaletteNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblSeriesRowsSeries {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legend", typeof(serviceServicePageTblSeriesRowsSeriesLegend))]
    [System.Xml.Serialization.XmlElementAttribute("serie", typeof(serviceServicePageTblSeriesRowsSeriesSerie))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblSeriesRowsSeriesLegend {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string htmlPathField;
    
    private bool collapsibleField;
    
    private bool collapsibleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string htmlPath {
        get {
            return this.htmlPathField;
        }
        set {
            this.htmlPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool collapsible {
        get {
            return this.collapsibleField;
        }
        set {
            this.collapsibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool collapsibleSpecified {
        get {
            return this.collapsibleFieldSpecified;
        }
        set {
            this.collapsibleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageTblSeriesRowsSeriesSerie {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    private string colorPaletteNameField;
    
    private string rulesetField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    private bool isInvisibleField;
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colorPaletteName {
        get {
            return this.colorPaletteNameField;
        }
        set {
            this.colorPaletteNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ruleset {
        get {
            return this.rulesetField;
        }
        set {
            this.rulesetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - start
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isInvisible
    {
        get
        {
            return this.isInvisibleField;
        }
        set
        {
            this.isInvisibleField = value;
        }
    }
    //Add for IM01977477:AIS - Modify kecp01fao publication - 20140802 - end
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageWindIcon {
    
    private serviceServicePageWindIconSerie[] seriesField;
    
    private string nameField;
    
    private string trnsTagField;
    
    private bool plotColumnHeaderField;
    
    private bool plotColumnHeaderFieldSpecified;
    
    private string dataSourceField;
    
    private sbyte startDateField;
    
    private sbyte endDateField;
    
    private string temporalAggregationField;
    
    private ushort widthField;
    
    private ushort heightField;
    
    private bool feedbackField;
    
    private bool feedbackFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serie", IsNullable=false)]
    public serviceServicePageWindIconSerie[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool plotColumnHeader {
        get {
            return this.plotColumnHeaderField;
        }
        set {
            this.plotColumnHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool plotColumnHeaderSpecified {
        get {
            return this.plotColumnHeaderFieldSpecified;
        }
        set {
            this.plotColumnHeaderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSource {
        get {
            return this.dataSourceField;
        }
        set {
            this.dataSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string temporalAggregation {
        get {
            return this.temporalAggregationField;
        }
        set {
            this.temporalAggregationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool feedback {
        get {
            return this.feedbackField;
        }
        set {
            this.feedbackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackSpecified {
        get {
            return this.feedbackFieldSpecified;
        }
        set {
            this.feedbackFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class serviceServicePageWindIconSerie {
    
    private string nameField;
    
    private string trnsTagField;
    
    private string aggregationFunctionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trnsTag {
        get {
            return this.trnsTagField;
        }
        set {
            this.trnsTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aggregationFunction {
        get {
            return this.aggregationFunctionField;
        }
        set {
            this.aggregationFunctionField = value;
        }
    }
}
